# Generated by Django 5.2.10 on 2026-01-09 10:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('admin_code', models.CharField(help_text='Internal SKU or Code', max_length=50, unique=True)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price in INR', max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('image_urls', models.JSONField(default=list, help_text='List of image URLs')),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='DimensionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_length', models.FloatField(help_text='Min Length in cm')),
                ('max_length', models.FloatField(help_text='Max Length in cm')),
                ('min_breadth', models.FloatField(help_text='Min Breadth in cm')),
                ('max_breadth', models.FloatField(help_text='Max Breadth in cm')),
                ('min_height', models.FloatField(help_text='Min Height in cm')),
                ('max_height', models.FloatField(help_text='Max Height in cm')),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplier for Base Price', max_digits=5)),
                ('price_add_on', models.DecimalField(decimal_places=2, default=0.0, help_text='Flat add-on cost in INR', max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_configs', to='products.product')),
            ],
        ),
    ]
