# Generated by Django 5.2.10 on 2026-01-10 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField(help_text='Length in cm')),
                ('breadth', models.FloatField(help_text='Breadth in cm')),
                ('height', models.FloatField(help_text='Height in cm')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price for this specific dimension', max_digits=10)),
                ('is_default', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='products.product')),
            ],
            options={
                'unique_together': {('product', 'length', 'breadth', 'height')},
            },
        ),
    ]
