# Generated by Django 5.2.10 on 2026-01-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_customizerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizerequest',
            name='admin_note',
            field=models.TextField(blank=True, help_text="Admin's internal note or rejection reason"),
        ),
        migrations.AlterField(
            model_name='customizerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWED', 'Reviewed'), ('CONTACTED', 'Contacted'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
