# Generated by Django 5.2.10 on 2026-01-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_image_urls_product_legacy_image_urls_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='legacy_image_urls',
            field=models.JSONField(blank=True, default=list, help_text='List of image URLs (Deprecated)'),
        ),
    ]
