# Generated by Django 4.2.7 on 2026-01-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_legacy_image_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizerequest',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed'), ('CONTACTED', 'Contacted'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='SUBMITTED', max_length=20),
        ),
    ]
