# Generated by Django 5.2.10 on 2026-01-10 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_cart_guest_email_cart_session_key_order_guest_email_and_more'),
        ('promotions', '0004_alter_mainbanner_redirect_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='applied_promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='promotions.promocode'),
        ),
    ]
