# Generated by Django 5.2.10 on 2026-01-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_cart_applied_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('ONLINE', 'Online Payment'), ('COD', 'Cash on Delivery')], default='ONLINE', max_length=10),
        ),
    ]
