# Generated by Django 5.2.10 on 2026-01-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_notified_status',
            field=models.CharField(blank=True, help_text='Last status for which SMS was sent', max_length=20, null=True),
        ),
    ]
