# Generated by Django 5.2.10 on 2026-01-10 09:21

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTaxInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstin', models.CharField(help_text='15-digit GSTIN', max_length=15, unique=True)),
                ('legal_name', models.CharField(max_length=255)),
                ('trade_name', models.CharField(max_length=255)),
                ('registered_address', models.TextField()),
                ('state_code', models.CharField(max_length=2)),
                ('state_name', models.CharField(default='Telangana', max_length=50)),
                ('pan', models.CharField(max_length=10)),
                ('is_composition_dealer', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Business Tax Info',
                'verbose_name_plural': 'Business Tax Info',
            },
        ),
        migrations.CreateModel(
            name='TaxCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('hsn_code', models.CharField(help_text='Harmonized System Nomenclature code', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('cgst_rate', models.DecimalField(decimal_places=2, help_text='Central GST rate (e.g., 9.00 for 9%)', max_digits=5)),
                ('sgst_rate', models.DecimalField(decimal_places=2, help_text='State GST rate (e.g., 9.00 for 9%)', max_digits=5)),
                ('igst_rate', models.DecimalField(decimal_places=2, help_text='Integrated GST rate (e.g., 18.00 for 18%)', max_digits=5)),
                ('cess_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Additional cess if applicable', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Tax Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaxExemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('exemption_type', models.CharField(choices=[('FULL', 'Full Exemption'), ('PARTIAL', 'Partial Exemption'), ('CATEGORY', 'Category-Based')], max_length=20)),
                ('exemption_percentage', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5)),
                ('applicable_states', models.JSONField(default=list, help_text='List of states where exemption applies')),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
