# Generated by Django 5.2.10 on 2026-01-09 11:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_mobile', models.CharField(help_text='Snapshot of user mobile', max_length=15)),
                ('user_role', models.CharField(max_length=20)),
                ('action', models.CharField(help_text='Action performed', max_length=100)),
                ('resource_type', models.CharField(help_text='Model name', max_length=50)),
                ('resource_id', models.CharField(help_text='Object ID', max_length=100)),
                ('changes', models.JSONField(blank=True, help_text='Before/after state', null=True)),
                ('reason', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('correlation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['resource_type', 'resource_id'], name='core_auditl_resourc_a674ad_idx'), models.Index(fields=['user', 'timestamp'], name='core_auditl_user_id_7b678c_idx'), models.Index(fields=['action'], name='core_auditl_action_d9fb24_idx')],
            },
        ),
    ]
