# Generated by Django 5.2.10 on 2026-01-10 17:45

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainBanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher number = Higher priority')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('image_url', models.URLField(help_text='URL to banner image')),
                ('cta_text', models.CharField(default='Shop Now', max_length=50)),
                ('redirect_url', models.CharField(help_text='Local path or absolute URL', max_length=500)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher number = Higher priority')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('image_url', models.URLField()),
                ('redirect_url', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScrollBanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher number = Higher priority')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(help_text='Text to display')),
                ('background_color', models.CharField(default='#000000', max_length=20)),
                ('text_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('link', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
                'abstract': False,
            },
        ),
    ]
