# Generated by Django 5.2.10 on 2026-01-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_mainbanner_promotion_scrollbanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainbanner',
            name='image_url',
            field=models.CharField(help_text='Image path or URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='image_url',
            field=models.CharField(help_text='Image path or URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='scrollbanner',
            name='link',
            field=models.CharField(blank=True, help_text='Local path or absolute URL', max_length=500, null=True),
        ),
    ]
