# Generated by Django 5.2.10 on 2026-01-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_alter_mainbanner_image_url_alter_promotion_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainbanner',
            name='redirect_url',
            field=models.CharField(blank=True, help_text='Local path or absolute URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='redirect_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
