# Generated by Django 5.2.10 on 2026-01-11 08:14

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_alter_mainbanner_redirect_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher number = Higher priority')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('popup_type', models.CharField(choices=[('IMAGE', 'Image Only'), ('TEXT', 'Text Only'), ('IMAGE_LINK', 'Image + Link'), ('TEXT_CTA', 'Text + CTA')], default='IMAGE', max_length=20)),
                ('content', models.TextField(blank=True, help_text='Text content (HTML allowed for safe tags)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='popups/')),
                ('redirect_url', models.CharField(blank=True, help_text='Link to redirect to', max_length=500, null=True)),
                ('cta_text', models.CharField(blank=True, default='Learn More', max_length=50)),
                ('display_rule', models.CharField(choices=[('ONCE_SESSION', 'Once per Session'), ('ONCE_USER', 'Once per User'), ('ALWAYS', 'Always')], default='ONCE_SESSION', max_length=20)),
                ('delay_seconds', models.IntegerField(default=0, help_text='Delay before showing (seconds)')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
                'abstract': False,
            },
        ),
    ]
