# Generated by Django 5.2.10 on 2026-01-10 09:21

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('rate_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4)),
                ('delivery_days_adjustment', models.IntegerField(default=0)),
                ('has_tracking', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('states', models.JSONField(default=list, help_text='List of state names covered by this zone')),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('min_order_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('max_order_value', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank for no upper limit', max_digits=10, null=True)),
                ('base_rate', models.DecimalField(decimal_places=2, help_text='Base shipping charge', max_digits=10)),
                ('per_kg_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Additional charge per kg after base weight', max_digits=10)),
                ('base_weight_kg', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Weight included in base rate', max_digits=5)),
                ('free_above', models.DecimalField(blank=True, decimal_places=2, help_text='Free shipping for orders above this amount', max_digits=10, null=True)),
                ('min_delivery_days', models.IntegerField(default=3)),
                ('max_delivery_days', models.IntegerField(default=7)),
                ('is_active', models.BooleanField(default=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='shipping.shippingzone')),
            ],
            options={
                'ordering': ['zone', 'min_order_value'],
            },
        ),
        migrations.CreateModel(
            name='PincodeServiceability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pincode', models.CharField(max_length=10, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('cod_available', models.BooleanField(default=True)),
                ('prepaid_only', models.BooleanField(default=False)),
                ('is_serviceable', models.BooleanField(default=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pincodes', to='shipping.shippingzone')),
            ],
            options={
                'ordering': ['pincode'],
            },
        ),
    ]
