# Generated by Django 5.2.10 on 2026-01-09 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='India', max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('lat_min', models.FloatField(blank=True, help_text='Southern boundary', null=True)),
                ('lat_max', models.FloatField(blank=True, help_text='Northern boundary', null=True)),
                ('long_min', models.FloatField(blank=True, help_text='Western boundary', null=True)),
                ('long_max', models.FloatField(blank=True, help_text='Eastern boundary', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_service_areas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['country', 'state', 'district', 'city'],
            },
        ),
        migrations.CreateModel(
            name='LocationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('submitted_timestamp', models.DateTimeField()),
                ('city', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('was_allowed', models.BooleanField()),
                ('denial_reason', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('correlation_id', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_attempts', to=settings.AUTH_USER_MODEL)),
                ('matched_service_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.servicearea')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CustomerLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accuracy', models.FloatField(help_text='GPS accuracy in meters')),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('full_address', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_location', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['is_verified', 'expires_at'], name='location_cu_is_veri_992173_idx'), models.Index(fields=['user', 'is_verified'], name='location_cu_user_id_31f761_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='servicearea',
            index=models.Index(fields=['is_active'], name='location_se_is_acti_14d873_idx'),
        ),
        migrations.AddIndex(
            model_name='servicearea',
            index=models.Index(fields=['state', 'district', 'city'], name='location_se_state_6b60ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='servicearea',
            unique_together={('country', 'state', 'district', 'city')},
        ),
        migrations.AddIndex(
            model_name='locationattempt',
            index=models.Index(fields=['user', 'timestamp'], name='location_lo_user_id_1f3706_idx'),
        ),
        migrations.AddIndex(
            model_name='locationattempt',
            index=models.Index(fields=['was_allowed', 'timestamp'], name='location_lo_was_all_3fa6e1_idx'),
        ),
        migrations.AddIndex(
            model_name='locationattempt',
            index=models.Index(fields=['-timestamp'], name='location_lo_timesta_18a9cf_idx'),
        ),
    ]
