"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent
APPS_DIR = BASE_DIR / "apps"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Razorpay Credentials (from environment)
RAZORPAY_KEY_ID = env('RAZORPAY_KEY_ID', default='rzp_test_placeholder')
RAZORPAY_KEY_SECRET = env('RAZORPAY_KEY_SECRET', default='secret_placeholder')

# MSG91 SMS Provider Configuration
SMS_ENABLED = env.bool('SMS_ENABLED', default=False)  # Feature flag
SMS_PROVIDER = env('SMS_PROVIDER', default='MSG91')
MSG91_AUTH_KEY = env('MSG91_AUTH_KEY', default='')
MSG91_SENDER_ID = env('MSG91_SENDER_ID', default='ECOMM')
MSG91_OTP_TEMPLATE_ID = env('MSG91_OTP_TEMPLATE_ID', default='')

# Frontend URL for order tracking links in SMS
FRONTEND_URL = env('FRONTEND_URL', default='http://localhost:8000')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #Third Party
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',

    # Local Apps
    'apps.core',
    'apps.authentication',
    'apps.products',
    'apps.orders',
    'apps.payments',
    'apps.location',
    'apps.taxation',
    'apps.shipping',
    'apps.promotions',
    'apps.notifications',
    
    # CORS
    'corsheaders',
]

MIDDLEWARE = [
    'apps.core.middleware.correlation.CorrelationIDMiddleware',  # First for all requests
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'apps.authentication.middleware.JWTCookieMiddleware', # Customer JWT Support for Templates
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.core.middleware.audit.AuditLogMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.core.cart_context.cart_count',
                'apps.promotions.context_processors.scroll_banner',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': env.db('DATABASE_URL', default='postgres://postgres:postgres@localhost:5432/ecommerce_db'),
    # SQLite Options for better concurrency in dev
    'OPTIONS': {
        'timeout': 20,  # Wait 20 seconds for lock release
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# DRF Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'apps.authentication.jwt_backend.BlacklistCheckingJWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '1000/day',
        'user': '1000/day',
        'otp': '20/min',  # Custom scope for OTP (Relaxed for Dev)
        'admin_notifications': '10/hour',  # Admin can send 10 notifications per hour
    },
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'EXCEPTION_HANDLER': 'apps.core.exceptions.custom_exception_handler',
}

# Custom User Model
AUTH_USER_MODEL = 'authentication.User'

# Redis Cache
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": env('REDIS_URL', default="redis://localhost:6379/1"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# JWT Configuration - Extended Token Lifetime for Stable Sessions
# Users stay logged in until explicit logout (manual only)
from datetime import timedelta

SIMPLE_JWT = {
    # Access tokens valid for 30 days (like modern ecommerce platforms)
    'ACCESS_TOKEN_LIFETIME': timedelta(days=30),
    
    # Refresh tokens valid for 90 days
    'REFRESH_TOKEN_LIFETIME': timedelta(days=90),
    
    # Rotate refresh tokens on refresh
    'ROTATE_REFRESH_TOKENS': True,
    
    # Blacklist old tokens after rotation
    'BLACKLIST_AFTER_ROTATION': True,
    
    # Algorithm for signing tokens
    'ALGORITHM': 'HS256',
    
    # Token header
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    
    # User ID claim
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    
    # Token types
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# =============================
# CELERY CONFIGURATION
# =============================

# Celery Broker and Result Backend (Redis)
CELERY_BROKER_URL = env('CELERY_BROKER_URL', default='redis://localhost:6379/1')
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default='redis://localhost:6379/2')

# Serialization (JSON only for security)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Kolkata'

# Task result expiration (7 days)
CELERY_RESULT_EXPIRES = 60 * 60 * 24 * 7

# Task routing (dedicated SMS queue)
CELERY_TASK_ROUTES = {
    'apps.core.tasks.send_sms_async': {'queue': 'sms'},
    'apps.core.tasks.send_otp_sms_async': {'queue': 'sms'},
}

# Reliability settings
CELERY_TASK_ACKS_LATE = True  # Acknowledge tasks after completion (prevents task loss)
CELERY_TASK_REJECT_ON_WORKER_LOST = True  # Requeue tasks if worker crashes

# =============================
# LOGGING CONFIGURATION
# =============================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'apps': {  # Your local apps
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'apps.core.services': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'celery': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}
