# Generated by Django 5.2.10 on 2026-01-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='Required for admin users. Used for admin login.', max_length=255, null=True, unique=True, verbose_name='email address'),
        ),
    ]
