# Generated by Django 5.2.10 on 2026-01-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_add_email_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='User profile photo', null=True, upload_to='profile_photos/'),
        ),
    ]
