# Generated by Django 5.2.10 on 2026-01-10 09:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=10)),
                ('event', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed'), ('QUEUED', 'Queued')], max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push Notification')], max_length=10)),
                ('event', models.CharField(choices=[('ORDER_CONFIRMED', 'Order Confirmed'), ('ORDER_SHIPPED', 'Order Shipped'), ('ORDER_DELIVERED', 'Order Delivered'), ('PAYMENT_FAILED', 'Payment Failed'), ('WELCOME', 'Welcome Email'), ('OTP', 'OTP Verification')], max_length=50)),
                ('subject', models.CharField(blank=True, help_text='Subject for Emails', max_length=255)),
                ('body', models.TextField(help_text='Content with {{ placeholders }}')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('type', 'event')},
            },
        ),
    ]
