# Generated by Django 5.2.10 on 2026-01-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='provider_response',
            field=models.JSONField(blank=True, help_text='MSG91 or other provider response', null=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('QUEUED', 'Queued'), ('RETRYING', 'Retrying')], default='PENDING', max_length=20),
        ),
    ]
